name: cache-tools-os2
description: Cache Optional Dependencies
inputs:
  arch:
    description: 'Architecture'
    default: ''
    required: false
    type: string
  id:
    description: 'Identification'
    default: ''
    required: false
    type: string
  nocache:
    description: 'skip cache'
    default: ''
    required: false
    type: string
#
# OS2TK45: https://88watts.net/dlfile.php?F=Os2Tk45-
#
# OS/2 Developer's Toolkit v4.5 is available on David Azarewicz's 88watts.net
# *supposedly* with permission from IBM - or so Arca Noae (which David is
# involved with) claims on this page:
#   https://www.arcanoae.com/wiki/information-for-developers/
# It is needed only for building the IBM TCP/IP 2.0 TCP/IP backend. The SDK
# for this is also available on the OS/2 Warp 4 CD.
#
#
# INFOZIP_FTP: ftp://ftp.info-zip.org/pub/infozip/
#   ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn.zip
#   ftp://ftp.info-zip.org/pub/infozip/os2/unz600.exe
#
# old: INFOZIP_FTP: https://ftp.zx.net.nz/pub/archive/ftp.info-zip.org/pub/infozip/
#
runs:
  using: composite
  steps:
    - name: Cache legacy dependencies
      if: inputs.nocache != 'true'
      uses: actions/cache@v4
      id: cache-os2
      with:
        path: |
          ${{github.workspace}}\info-zip
          ${{github.workspace}}\os2tk45
        key: all-build-tools-os2
    - name: Get and unpack OS/2 toolkit 4.5
      if: steps.cache-os2.outputs.cache-hit != 'true'
      run: |
        curl -LsS -o os2tk45.zip https://88watts.net/dlfile.php?F=Os2Tk45-
        7z x os2tk45.zip
        rm -f os2tk45.zip
        mv toolkit/os2tk45 os2tk45
        mv os2tk45/h os2tk45/include
        echo "content of os2tk45"
        ls -l os2tk45
      shell: bash       
    - name: Get and unpack Info-zip
      if: steps.cache-os2.outputs.cache-hit != 'true'
      run: |
        mkdir -p info-zip/os2
        curl -LsS -o zip.zip ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn.zip
        7z x zip.zip -oinfo-zip
        rm -f zip.zip
        echo "content of info-zip"
        ls -l info-zip
        curl -LsS -o unzip.zip ftp://ftp.info-zip.org/pub/infozip/os2/unz600.exe
        7z x unzip.zip -oinfo-zip/os2
        rm -f unzip.zip
        mv info-zip/os2/32-bit/* info-zip/os2
        echo "content of info-zip/os2"
        ls -l info-zip/os2
      shell: bash       
