name: libssh-get
description: 'Download libssh'
#
# download from https://www.libssh.org/files/
#
# expected filenames:
#   https://www.libssh.org/files/0.10/libssh-0.10.6.tar.xz
#
inputs:
  id:
    description: 'Identification'
    default: ''
runs:
  using: composite
  steps:
    - run: mkdir -p libssh
      shell: bash
    - name: get url
      id: geturl
      env:
        LIBSSHVER: ${{ inputs.id }}
      run: |
        echo "url=https://www.libssh.org/files/${LIBSSHVER%.*}/libssh-${{ inputs.id }}.tar.xz" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: download libssh
      uses: "./.github/actions/curl-cmd"
      with:
        local: libssh-${{ inputs.id }}.tar.xz
        remote: ${{ steps.geturl.outputs.url }}
    - name: unpack libssh
      run: |
        7z x libssh-${{ inputs.id }}.tar.xz
        7z x libssh-${{ inputs.id }}.tar -olibssh
        rm -f libssh-${{ inputs.id }}.tar libssh-${{ inputs.id }}.tar.xz
        mv libssh/libssh-${{ inputs.id }} libssh/current
        mkdir -p libssh/current/build
      shell: bash
