name: libsrp-get
description: 'Download libsrp'
#
# download from http://srp.stanford.edu/source/
#
# expected filenames:
#   http://srp.stanford.edu/source/srp-2.1.2.tar.gz
#
inputs:
  id:
    description: 'Identification'
    default: ''
runs:
  using: composite
  steps:
    - name: download libsrp
      uses: "./.github/actions/curl-cmd"
      with:
        local: srp-2.1.2.tar.gz
        remote: http://srp.stanford.edu/source/srp-2.1.2.tar.gz
    - name: unpack libsrp
      run: |
        7z x srp-2.1.2.tar.gz
        7z x srp-2.1.2.tar
        rm -f srp-2.1.2.tar srp-2.1.2.tar.gz
        mv srp-2.1.2 libsrp
        cp srp/* libsrp
      shell: bash
