name: os2tk45-get
description: 'Download os2tk45'
#
# OS2TK45: https://88watts.net/dlfile.php?F=Os2Tk45-
#
# OS/2 Developer's Toolkit v4.5 is available on David Azarewicz's 88watts.net
# *supposedly* with permission from IBM - or so Arca Noae (which David is
# involved with) claims on this page:
#   https://www.arcanoae.com/wiki/information-for-developers/
# It is needed only for building the IBM TCP/IP 2.0 TCP/IP backend. The SDK
# for this is also available on the OS/2 Warp 4 CD.
#
inputs:
  arch:
    description: 'Architecture for download'
    default: ''
    required: false
    type: string
  ver:
    description: 'Version for download'
    default: ''
    required: false
    type: string
runs:
  using: composite
  steps:
    - name: download and extract
      run: |
        curl -LsS -o os2tk45.zip https://88watts.net/dlfile.php?F=Os2Tk45-
        7z x os2tk45.zip
        mv toolkit/os2tk45/h toolkit/os2tk45/include
        rm -f os2tk45.zip
        echo "content of toolkit/os2tk45"
        ls -l toolkit/os2tk45
      shell: bash       
