name: cache-os2-tools
description: Cache OS/2 tools
inputs:
  nocache:
    description: 'skip cache'
    default: ''
    required: false
    type: string
#
# OS/2 Developer's Toolkit v4.5 is available on David Azarewicz's 88watts.net
# *supposedly* with permission from IBM - or so Arca Noae (which David is
# involved with) claims on this page:
#   https://www.arcanoae.com/wiki/information-for-developers/
# It is needed only for building the IBM TCP/IP 2.0 TCP/IP backend. The SDK
# for this is also available on the OS/2 Warp 4 CD.
#
# expected filename: https://88watts.net/dlfile.php?F=Os2Tk45-
#
# InfoZip
# alternate site: https://ftp.zx.net.nz/pub/archive/ftp.info-zip.org/pub/infozip/
#
# expected filename: ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn.zip
# expected filename: ftp://ftp.info-zip.org/pub/infozip/os2/unz600.exe
#
runs:
  using: composite
  steps:
    - name: Load Cache OS/2 tools
      if: inputs.nocache != 'true'
      uses: actions/cache@v4
      id: cache-os2
      with:
        path: |
          ${{github.workspace}}/info-zip
          ${{github.workspace}}/os2tk45
        key: all-infozip+os2tk45
    - name: Get and unpack Info-Zip
      if: steps.cache-os2.outputs.cache-hit != 'true'
      run: |
        mkdir -p info-zip/os2
        curl -LsS -o zip.zip ftp://ftp.info-zip.org/pub/infozip/win32/zip300xn.zip
        7z x zip.zip -oinfo-zip
        rm -f zip.zip
        curl -LsS -o unzip.zip ftp://ftp.info-zip.org/pub/infozip/os2/unz600.exe
        7z x unzip.zip -oinfo-zip/os2
        rm -f unzip.zip
        mv info-zip/os2/32-bit/* info-zip/os2/
        echo "content of info-zip/os2"
        ls -l info-zip/os2
        echo "content of info-zip"
        ls -l info-zip
      shell: bash
    - name: Get and unpack IBM OS/2 4.5 toolkit
      if: steps.cache-os2.outputs.cache-hit != 'true'
      run: |
        curl -LsS -o os2tk45.zip https://88watts.net/dlfile.php?F=Os2Tk45-
        7z x os2tk45.zip
        rm -f os2tk45.zip
        mv toolkit/os2tk45 os2tk45
        mv os2tk45/h os2tk45/include
        echo "content of os2tk45"
        ls -l os2tk45
      shell: bash
