name: cache-psdk71-vc10-deps
description: Handle Dependencies Cache psdk71-vc10
runs:
  using: composite
  steps:
      - name: Cache Compiler
        uses: "./.github/actions/cache"
        id: cache-deps
        with:
          path: |
            ${{github.workspace}}\Microsoft SDKs 
            ${{github.workspace}}\Microsoft Visual Studio 10.0
            ${{github.workspace}}\vc10.cmd
            ${{github.workspace}}\vcredist_x86.exe
          key: platform-sdk-71-compiler+sdk+redist
      - name: Get Windows 7 Platform SDK v7.1
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          curl ${{ env.CK_CURL }} -o win7-7.1-sdk-vc.7z https://ftp.zx.net.nz/pub/dev/WinSDK/win7-7.1-dn4/win7-7.1-sdk-vc.7z
          7z x win7-7.1-sdk-vc.7z
          rm win7-7.1-sdk-vc.7z
          
          curl ${{ env.CK_CURL }} -o win7-7.1-sdk-psdk.7z https://ftp.zx.net.nz/pub/dev/WinSDK/win7-7.1-dn4/win7-7.1-sdk-psdk.7z
          7z x win7-7.1-sdk-psdk.7z
          rm win7-7.1-sdk-psdk.7z
          
          curl ${{ env.CK_CURL }} -o vcredist_x86.exe http://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe
        shell: bash

