name: nasm-get
description: 'Download nasm'
#
# NASM: https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
#
inputs:
  arch:
    description: 'Architecture for download'
    default: ''
    required: false
    type: string
  ver:
    description: 'Version for download'
    default: ''
    required: false
    type: string
runs:
  using: composite
  steps:
    - name: create directory if not exists
      run: mkdir -p tools
      shell: bash
    - name: download and extract nasm
      working-directory: tools
      run: |
        curl -LsS -o nasm-2.15.05-win32.zip https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
        7z x nasm-2.15.05-win32.zip
        mv nasm-2.15.05 ${{ inputs.ver }}
        rm nasm-2.15.05-win32.zip
      shell: bash       
