name: cache-vct2003-libdes-deps
description: Cache Optional Dependencies
inputs:
  arch:
    description: 'Architecture for download'
    default: ''
    required: false
    type: string
  id:
    description: 'Identification'
    default: ''
    required: false
    type: string
  nocache:
    description: 'skip cache'
    default: ''
    required: false
    type: string
runs:
  using: composite
  steps:
      - name: Cache VCT2003+libdes
        uses: "./.github/actions/cache"
        id: cache-deps
        with:
          path: |
            ${{github.workspace}}\vct2003
            ${{github.workspace}}\libdes\des
            ${{github.workspace}}\libdes\Release
            ${{github.workspace}}\libdes\Debug
            ${{github.workspace}}\tools
          key: vct2003+psdk2003sp1+libdes+v2+jom1
          nocache: ${{ inputs.nocache }}
      - name: Get jom
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: "./.github/actions/jom-get"
      - name: Get libdes
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: "./.github/actions/libdes-get"
      - name: Get Visual C++ 2003 Toolkit + Platform SDK 2003
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: "./.github/actions/vct2003-get"
