name: cache-mingw-deps
description: Cache Optional Dependencies
inputs:
  arch:
    description: 'Architecture for download'
    default: ''
    required: false
    type: string
  id:
    description: 'Identification'
    default: ''
    required: false
    type: string
  nocache:
    description: 'skip cache'
    default: ''
    required: false
    type: string
runs:
  using: composite
  steps:
      - name: Cache Dependencies
        uses: "./.github/actions/cache"
        id: cache-deps
        with:
          path: |
            ${{github.workspace}}/openssl/current
            ${{github.workspace}}/libssh
            ${{github.workspace}}/zlib
          key: deps-openssl-${{env.CK_OPENSSL_VERSION}}-parallel-v1
          nocache: ${{ inputs.nocache }}
      - name: Get and unpack openssl
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: "./.github/actions/openssl-get"

      - name: Build openssl
        if: steps.cache-deps.outputs.cache-hit != 'true'
        env:
          CXX: /usr/bin/x86_64-w64-mingw32-c++
          CC: /usr/bin/x86_64-w64-mingw32-gcc
          RC: /usr/bin/x86_64-w64-mingw32-windres
        working-directory: openssl/current
        run: |
          perl Configure mingw64
          make depend
          make -j 2
        shell: bash
