name: jom-get
description: 'Download jom'
runs:
  using: composite
  steps:
      - run: mkdir -p tools
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
      - name: Get and unpack jom
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: tools
        run: |
          mkdir -p jom
          curl ${{ env.CK_CURL }} -o jom.zip ${{env.JOM}} -L
          7z x jom.zip -ojom
          rm -f jom.zip
        shell: bash
