name: jom-get
description: 'Download jom'
#
# JOM: https://download.qt.io/official_releases/jom/jom.zip
#
inputs:
  arch:
    description: 'Architecture for download'
    default: ''
    required: false
    type: string
  ver:
    description: 'Version for download'
    default: ''
    required: false
    type: string
runs:
  using: composite
  steps:
    - name: create directory if not exists
      run: mkdir -p tools/${{ inputs.ver }}
      shell: bash
    - name: download and extract jom
      working-directory: tools
      run: |
        curl -LsS -o jom.zip https://download.qt.io/official_releases/jom/jom.zip
        7z x jom.zip -o ${{ inputs.ver }}
        rm jom.zip
      shell: bash       
