name: jom-get
description: 'Download jom'
#
# download from https://download.qt.io/official_releases/jom/
#
# expected filenames:
#   https://download.qt.io/official_releases/jom/jom.zip
#
inputs:
  id:
    description: 'Identification'
    default: ''
runs:
  using: composite
  steps:
    - run: mkdir -p tools/jom
      shell: bash
    - name: download jom.zip
      uses: "./.github/actions/curl-cmd"
      with:
        local: jom.zip
        remote: https://download.qt.io/official_releases/jom/jom.zip
    - name: unpack file
      run: |
        7z x jom.zip -otools/jom
        rm -f jom.zip
      shell: bash
