name: superlat-get
description: 'Download superlat'
#
# download from https://web.archive.org/web/20000929005919if_/http://www.meridian.com:80/
#
# expected filenames:
#   https://web.archive.org/web/20000929005919if_/http://www.meridian.com:80/slatfio.zip
#
inputs:
  id:
    description: 'Identification'
    default: ''
runs:
  using: composite
  steps:
    - run: mkdir -p superlat/include
      shell: bash
    - name: download superlat
      uses: "./.github/actions/curl-cmd"
      with:
        local: slatfio.zip
        remote: https://web.archive.org/web/20000929005919if_/http://www.meridian.com:80/slatfio.zip
    - name: unpack superlat
      run: |
        7z x slatfio.zip -osuperlat
        rm -f slatfio.zip
        cp superlat/TESTSVC/LATIOC.H superlat/include
        cp superlat/TESTSVC/NETTYPES.H superlat/include
        cp superlat/TESTSVC/NTDDTDI.H superlat/include
        cp superlat/TESTSVC/PACKOFF.H superlat/include
        cp superlat/TESTSVC/PACKON.H superlat/include
        cp superlat/TESTSVC/TDI.H superlat/include
        cp superlat/TESTSVC/TIHDR.H superlat/include
        rm -rf superlat/TESTSVC
        rm -rf superlat/CONN
        rm -f superlat/README.1ST
      shell: bash
