name: cache-ow-tools
description: Cache Open WatcomCompiler
inputs:
  id:
    description: 'Identification'
    default: ''
    required: false
    type: string
  nocache:
    description: 'skip cache'
    default: ''
    required: false
    type: string
  ver:
    description: 'Open Watcom version'
    default: ''
    required: false
    type: string
#
# expected filename: https://github.com/open-watcom/open-watcom-1.9/releases/download/ow1.9/open-watcom-c-linux-1.9
# expected filename: https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.xz
#
runs:
  using: composite
  steps:
    - name: Cache Open Watcom
      if: inputs.nocache != 'true'
      uses: actions/cache@v4
      id: cache-ow
      with:
        path: ${{github.workspace}}/watcom
        key: all-openwatcom-${{inputs.ver}}
    - name: Get and unpack Open Watcom
      if: steps.cache-ow.outputs.cache-hit != 'true'
      run: |
        mkdir -p watcom
        if [[ "${{inputs.ver}}" = "2.0" ]]; then
          curl -LsS -o ow-snapshot.tar.xz https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.xz
          7z x ow-snapshot.tar.xz
          7z x ow-snapshot.tar -owatcom
          rm -f ow-snapshot.tar.xz ow-snapshot.tar
        else
          curl -LsS -o ow.zip https://github.com/open-watcom/open-watcom-1.9/releases/download/ow1.9/open-watcom-c-linux-1.9
          7z x ow.zip -owatcom
          rm -f ow.zip
        fi
        echo "content of watcom"
        ls -l watcom
      shell: bash
    - name: Set Open Watcom Environment (Windows)
      if: runner.os == 'Windows'
      run: |
        echo WATCOM=${{github.workspace}}\watcom>> "%GITHUB_ENV%"
        echo ${{github.workspace}}\watcom\binw>> "%GITHUB_PATH%"
        echo ${{github.workspace}}\watcom\binnt>> "%GITHUB_PATH%"
        if "${{inputs.id}}" == "os2" echo INCLUDE=${{github.workspace}}\watcom\h;${{github.workspace}}\watcom\h\os2>> "%GITHUB_ENV%"
        if not "${{inputs.id}}" == "os2" echo INCLUDE=${{github.workspace}}\watcom\h;${{github.workspace}}\watcom\h\nt>> "%GITHUB_ENV%"
      shell: cmd
    - name: Set Open Watcom Environment (Linux)
      if: runner.os != 'Windows'
      run: |
        echo "WATCOM=${{github.workspace}}/watcom">> "$GITHUB_ENV"
        echo "${{github.workspace}}/watcom/binw">> "$GITHUB_PATH"
        echo "${{github.workspace}}/watcom/binl">> "$GITHUB_PATH"
        if [[ "${{inputs.id}}" = "os2" ]]; then
          echo "INCLUDE=${{github.workspace}}/watcom/h:${{github.workspace}}/watcom/h/os2">> "$GITHUB_ENV"
        else
          echo "INCLUDE=${{github.workspace}}/watcom/h:${{github.workspace}}/watcom/h/nt">> "$GITHUB_ENV"
        fi
      shell: bash
